DROP VIEW V_PI_HISTORY_DISTINCT_NODES;

/* Formatted on 28.05.2015 06:41:23 (QP5 v5.256.13226.35510) */
CREATE OR REPLACE FORCE VIEW V_PI_HISTORY_DISTINCT_NODES
(
   LOGDATE,
   DISTINCT_NODES
)
AS
     SELECT LOGDATE, COUNT (DISTINCT nodename) DISTINCT_NODES
       FROM (SELECT TO_CHAR (START_TIME, 'YYYY-MM-DD') LOGDATE, NODENAME
               FROM process_information_history)
   GROUP BY LOGDATE
   ORDER BY LOGDATE DESC;
